name: motoriders_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  crypto: ^3.0.3
  http: ^1.6.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  image_picker: ^1.2.1
  cached_network_image: ^3.3.1
  chewie: ^1.7.5
  video_player: ^2.8.6
  flutter_secure_storage: ^9.2.4
  web_socket_channel: ^3.0.3
  intl: ^0.20.2
  timeago: ^3.7.1
  share_plus: ^12.0.1
  jwt_decoder: ^2.0.1
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/utils/map_style.json
